using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Media;
using System.Windows.Threading;

namespace Lager_automation.Views
{
    /// <summary>
    /// Interaction logic for InputDataTemplateWindow.xaml
    /// </summary>
    public partial class InputDataTemplateWindow : Window
    {
        private readonly DataTable _table;
        private ICollectionView _view;
        private readonly Dictionary<string, HashSet<string>> _columnFilters = new();

        public InputDataTemplateWindow(DataTable table)
        {
            InitializeComponent();

            _table = table;
            TemplateDataGrid.ItemsSource = _table.DefaultView;
        }

        private bool RowFilter(object item)
        {
            if (item is not DataRowView row)
                return false;

            foreach (var filter in _columnFilters)
            {
                if (filter.Value.Count == 0)
                    continue;

                string cellValue = row[filter.Key]?.ToString() ?? "";

                if (!filter.Value.Contains(cellValue))
                    return false;
            }

            return true;
        }

        private void TemplateDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            foreach (var col in TemplateDataGrid.Columns)
            {
                var colName = col.Header?.ToString() ?? "";
                col.Header = CreateFilterHeader(colName);
            }
        }

        private object CreateFilterHeader(string columnName)
        {
            var panel = new StackPanel { Orientation = Orientation.Horizontal };
            panel.Children.Add(new TextBlock { Text = columnName, Margin = new Thickness(0, 0, 6, 0) });

            var btn = new Button
            {
                Content = "▼",
                Width = 18,
                Height = 18,
                Padding = new Thickness(0),
                Tag = columnName
            };
            btn.Click += OpenFilterPopup;

            panel.Children.Add(btn);
            return panel;
        }

        private void OpenFilterPopup(object sender, RoutedEventArgs e)
        {
            var button = (Button)sender;
            string column = (string)button.Tag;

            // Get distinct values safely from DataTable
            var distinct = _table.DefaultView.ToTable(true, column);
            var values = distinct.Rows.Cast<DataRow>()
                .Select(r => r[0]?.ToString() ?? "")
                .OrderBy(v => v)
                .ToList();

            if (!_columnFilters.ContainsKey(column))
                _columnFilters[column] = new HashSet<string>(values); // default = all selected

            var panel = new StackPanel { Background = Brushes.White };

            foreach (var value in values)
            {
                var cb = new CheckBox
                {
                    Content = value,
                    IsChecked = _columnFilters[column].Contains(value)
                };

                cb.Checked += (_, __) => { _columnFilters[column].Add(value); ApplyRowFilter(); };
                cb.Unchecked += (_, __) => { _columnFilters[column].Remove(value); ApplyRowFilter(); };

                panel.Children.Add(cb);
            }

            var popup = new Popup
            {
                PlacementTarget = button,
                Placement = PlacementMode.Bottom,
                StaysOpen = false,
                IsOpen = true,
                Child = new Border
                {
                    BorderBrush = Brushes.Gray,
                    BorderThickness = new Thickness(1),
                    Background = Brushes.White,
                    Child = new ScrollViewer { Content = panel, MaxHeight = 300, Width = 220 }
                }
            };
        }


        private void ApplyFilter(string column, string value, bool include)
        {
            if (include)
                _columnFilters[column].Add(value);
            else
                _columnFilters[column].Remove(value);

            _view.Refresh();
        }

        private void ApplyRowFilter()
        {
            // If any column has 0 selected values => show nothing (Excel behavior)
            foreach (var kv in _columnFilters)
            {
                if (kv.Value.Count == 0)
                {
                    _table.DefaultView.RowFilter = "1 = 0";
                    return;
                }
            }

            var sb = new StringBuilder();

            foreach (var kv in _columnFilters)
            {
                string col = kv.Key;
                var allowed = kv.Value;

                // If "all values" selected, skip adding filter for that column
                // (We detect this by comparing against distinct list size)
                var distinctCount = _table.DefaultView.ToTable(true, col).Rows.Count;
                if (allowed.Count == distinctCount)
                    continue;

                if (sb.Length > 0)
                    sb.Append(" AND ");

                sb.Append("(");

                bool first = true;
                foreach (var v in allowed)
                {
                    if (!first) sb.Append(" OR ");
                    first = false;

                    // Escape single quotes for RowFilter syntax
                    var escaped = v.Replace("'", "''");
                    sb.AppendFormat("[{0}] = '{1}'", col.Replace("]", "]]"), escaped);
                }

                sb.Append(")");
            }

            _table.DefaultView.RowFilter = sb.ToString();
        }

    }
}
